# Configurações de produção


# Conexão com MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/loja
spring.datasource.username=root
spring.datasource.password=root


# Recriar banco de dados ao iniciar aplicao: nunca
spring.sql.init.mode=never