spring.application.name=Loja WebFrameworks

# Driver MySQL
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Perfil ativo
spring.profiles.active=dev

